const currency = [
  {
    id: "AED",
    code: "AED",
    description: "United Arab Emirates Dirham",
    kind: "fiat",
    logoid: "country/AE",
  },
  {
    id: "AFN",
    code: "AFN",
    description: "Afghan Afghani",
    kind: "fiat",
    logoid: "country/AF",
  },
  {
    id: "ALL",
    code: "ALL",
    description: "Albanian Lek",
    kind: "fiat",
    logoid: "country/AL",
  },
  {
    id: "AMD",
    code: "AMD",
    description: "Armenian Dram",
    kind: "fiat",
    logoid: "country/AM",
  },
  {
    id: "ANG",
    code: "ANG",
    description: "Netherlands Antillean Guilder",
    kind: "fiat",
    logoid: "country/CW",
  },
  {
    id: "AOA",
    code: "AOA",
    description: "Angolan Kwanza",
    kind: "fiat",
    logoid: "country/AO",
  },
  {
    id: "ARS",
    code: "ARS",
    description: "Argentine Peso",
    kind: "fiat",
    logoid: "country/AR",
  },
  {
    id: "AUD",
    code: "AUD",
    description: "Australian Dollar",
    kind: "fiat",
    logoid: "country/AU",
  },
  {
    id: "AWG",
    code: "AWG",
    description: "Aruban Florin",
    kind: "fiat",
    logoid: "country/AW",
  },
  {
    id: "AVEXDL",
    code: "AVEXDL",
    description: "AVEXF",
  },
  {
    id: "AZN",
    code: "AZN",
    description: "Azerbaijani Manat",
    kind: "fiat",
    logoid: "country/AZ",
  },
  {
    id: "BAM",
    code: "BAM",
    description: "Bosnia-Herzegovina Convertible Mark",
    kind: "fiat",
    logoid: "country/BA",
  },
  {
    id: "BBD",
    code: "BBD",
    description: "Barbadian Dollar",
    kind: "fiat",
    logoid: "country/BB",
  },
  {
    id: "BDT",
    code: "BDT",
    description: "Bangladeshi Taka",
    kind: "fiat",
    logoid: "country/BD",
  },
  {
    id: "BGN",
    code: "BGN",
    description: "Bulgarian Lev",
    kind: "fiat",
    logoid: "country/BG",
  },
  {
    id: "BHD",
    code: "BHD",
    description: "Bahraini Dinar",
    kind: "fiat",
    logoid: "country/BH",
  },
  {
    id: "BIF",
    code: "BIF",
    description: "Burundian Franc",
    kind: "fiat",
    logoid: "country/BI",
  },
  {
    id: "BMD",
    code: "BMD",
    description: "Bermudan Dollar",
    kind: "fiat",
    logoid: "country/BM",
  },
  {
    id: "BND",
    code: "BND",
    description: "Brunei Dollar",
    kind: "fiat",
    logoid: "country/BN",
  },
  {
    id: "BOB",
    code: "BOB",
    description: "Bolivian Boliviano",
    kind: "fiat",
    logoid: "country/BO",
  },
  {
    id: "BRL",
    code: "BRL",
    description: "Brazilian Real",
    kind: "fiat",
    logoid: "country/BR",
  },
  {
    id: "BSD",
    code: "BSD",
    description: "Bahamian Dollar",
    kind: "fiat",
    logoid: "country/BS",
  },
  {
    id: "BTN",
    code: "BTN",
    description: "Bhutanese Ngultrum",
    kind: "fiat",
    logoid: "country/BT",
  },
  {
    id: "BWP",
    code: "BWP",
    description: "Botswanan Pula",
    kind: "fiat",
    logoid: "country/BW",
  },
  {
    id: "BYN",
    code: "BYN",
    description: "Belarusian Ruble",
    kind: "fiat",
    logoid: "country/BY",
  },
  {
    id: "BZD",
    code: "BZD",
    description: "Belize Dollar",
    kind: "fiat",
    logoid: "country/BZ",
  },
  {
    id: "CAD",
    code: "CAD",
    description: "Canadian Dollar",
    kind: "fiat",
    logoid: "country/CA",
  },
  {
    id: "CDF",
    code: "CDF",
    description: "Congolese Franc",
    kind: "fiat",
    logoid: "country/CD",
  },
  {
    id: "CELEST",
    code: "CELEST",
    description: "TIAUSD",
  },
  {
    id: "CHF",
    code: "CHF",
    description: "Swiss Franc",
    kind: "fiat",
    logoid: "country/CH",
  },
  {
    id: "CLF",
    code: "CLF",
    description: "Chilean Unit of Account (UF)",
    kind: "fiat",
    logoid: "country/CL",
  },
  {
    id: "CLP",
    code: "CLP",
    description: "Chilean Peso",
    kind: "fiat",
    logoid: "country/CL",
  },
  {
    id: "CNY",
    code: "CNY",
    description: "Chinese Yuan",
    kind: "fiat",
    logoid: "country/CN",
  },
  {
    id: "COP",
    code: "COP",
    description: "Colombian Peso",
    kind: "fiat",
    logoid: "country/CO",
  },
  {
    id: "CRC",
    code: "CRC",
    description: "Costa Rican Colón",
    kind: "fiat",
    logoid: "country/CR",
  },
  {
    id: "CUP",
    code: "CUP",
    description: "Cuban Peso",
    kind: "fiat",
    logoid: "country/CU",
  },
  {
    id: "CVE",
    code: "CVE",
    description: "Cape Verdean Escudo",
    kind: "fiat",
    logoid: "country/CV",
  },
  {
    id: "CZK",
    code: "CZK",
    description: "Czech Koruna",
    kind: "fiat",
    logoid: "country/CZ",
  },
  {
    id: "DJF",
    code: "DJF",
    description: "Djiboutian Franc",
    kind: "fiat",
    logoid: "country/DJ",
  },
  {
    id: "DKK",
    code: "DKK",
    description: "Danish Krone",
    kind: "fiat",
    logoid: "country/DK",
  },
  {
    id: "DOP",
    code: "DOP",
    description: "Dominican Peso",
    kind: "fiat",
    logoid: "country/DO",
  },
  {
    id: "DZD",
    code: "DZD",
    description: "Algerian Dinar",
    kind: "fiat",
    logoid: "country/DZ",
  },
  {
    id: "EGP",
    code: "EGP",
    description: "Egyptian Pound",
    kind: "fiat",
    logoid: "country/EG",
  },
  {
    id: "ERN",
    code: "ERN",
    description: "Eritrean Nakfa",
    kind: "fiat",
    logoid: "country/ER",
  },
  {
    id: "ETB",
    code: "ETB",
    description: "Ethiopian Birr",
    kind: "fiat",
    logoid: "country/ET",
  },
  {
    id: "EUR",
    code: "EUR",
    description: "Euro",
    kind: "fiat",
    logoid: "country/EU",
  },
  {
    id: "FJD",
    code: "FJD",
    description: "Fijian Dollar",
    kind: "fiat",
    logoid: "country/FJ",
  },
  {
    id: "FJO",
    code: "FJO",
    description: "FJOUSDT",
    kind: "fiat",
    logoid: "country/FJ",
  },
  {
    id: "GBP",
    code: "GBP",
    description: "British Pound",
    kind: "fiat",
    logoid: "country/GB",
  },
  {
    id: "GEL",
    code: "GEL",
    description: "Georgian Lari",
    kind: "fiat",
    logoid: "country/GE",
  },
  {
    id: "GHS",
    code: "GHS",
    description: "Ghanaian Cedi",
    kind: "fiat",
    logoid: "country/GH",
  },
  {
    id: "GIP",
    code: "GIP",
    description: "Gibraltar Pound",
    kind: "fiat",
    logoid: "country/GI",
  },
  {
    id: "GMD",
    code: "GMD",
    description: "Gambian Dalasi",
    kind: "fiat",
    logoid: "country/GM",
  },
  {
    id: "GNF",
    code: "GNF",
    description: "Guinean Franc",
    kind: "fiat",
    logoid: "country/GN",
  },
  {
    id: "GTQ",
    code: "GTQ",
    description: "Guatemalan Quetzal",
    kind: "fiat",
    logoid: "country/GT",
  },
  {
    id: "GYD",
    code: "GYD",
    description: "Guyanaese Dollar",
    kind: "fiat",
    logoid: "country/GY",
  },
  {
    id: "HKD",
    code: "HKD",
    description: "Hong Kong Dollar",
    kind: "fiat",
    logoid: "country/HK",
  },
  {
    id: "HNL",
    code: "HNL",
    description: "Honduran Lempira",
    kind: "fiat",
    logoid: "country/HN",
  },
  {
    id: "HTG",
    code: "HTG",
    description: "Haitian Gourde",
    kind: "fiat",
    logoid: "country/HT",
  },
  {
    id: "HUF",
    code: "HUF",
    description: "Hungarian Forint",
    kind: "fiat",
    logoid: "country/HU",
  },
  {
    id: "IDR",
    code: "IDR",
    description: "Indonesian Rupiah",
    kind: "fiat",
    logoid: "country/ID",
  },
  {
    id: "ILS",
    code: "ILS",
    description: "Israeli New Shekel",
    kind: "fiat",
    logoid: "country/IL",
  },
  {
    id: "INR",
    code: "INR",
    description: "Indian Rupee",
    kind: "fiat",
    logoid: "country/IN",
  },
  {
    id: "IQD",
    code: "IQD",
    description: "Iraqi Dinar",
    kind: "fiat",
    logoid: "country/IQ",
  },
  {
    id: "IRR",
    code: "IRR",
    description: "Iranian Rial",
    kind: "fiat",
    logoid: "country/IR",
  },
  {
    id: "ISK",
    code: "ISK",
    description: "Icelandic Króna",
    kind: "fiat",
    logoid: "country/IS",
  },
  {
    id: "JMD",
    code: "JMD",
    description: "Jamaican Dollar",
    kind: "fiat",
    logoid: "country/JM",
  },
  {
    id: "JOD",
    code: "JOD",
    description: "Jordanian Dinar",
    kind: "fiat",
    logoid: "country/JO",
  },
  {
    id: "JPY",
    code: "JPY",
    description: "Japanese Yen",
    kind: "fiat",
    logoid: "country/JP",
  },
  {
    id: "KES",
    code: "KES",
    description: "Kenyan Shilling",
    kind: "fiat",
    logoid: "country/KE",
  },
  {
    id: "KGS",
    code: "KGS",
    description: "Kyrgystani Som",
    kind: "fiat",
    logoid: "country/KG",
  },
  {
    id: "KHR",
    code: "KHR",
    description: "Cambodian Riel",
    kind: "fiat",
    logoid: "country/KH",
  },
  {
    id: "KMF",
    code: "KMF",
    description: "Comorian Franc",
    kind: "fiat",
    logoid: "country/KM",
  },
  {
    id: "KPW",
    code: "KPW",
    description: "North Korean Won",
    kind: "fiat",
    logoid: "country/KP",
  },
  {
    id: "KRW",
    code: "KRW",
    description: "South Korean Won",
    kind: "fiat",
    logoid: "country/KR",
  },
  {
    id: "KWD",
    code: "KWD",
    description: "Kuwaiti Dinar",
    kind: "fiat",
    logoid: "country/KW",
  },
  {
    id: "KYD",
    code: "KYD",
    description: "Cayman Islands Dollar",
    kind: "fiat",
    logoid: "country/KY",
  },
  {
    id: "KZT",
    code: "KZT",
    description: "Kazakhstani Tenge",
    kind: "fiat",
    logoid: "country/KZ",
  },
  {
    id: "LAK",
    code: "LAK",
    description: "Laotian Kip",
    kind: "fiat",
    logoid: "country/LA",
  },
  {
    id: "LBP",
    code: "LBP",
    description: "Lebanese Pound",
    kind: "fiat",
    logoid: "country/LB",
  },
  {
    id: "LKR",
    code: "LKR",
    description: "Sri Lankan Rupee",
    kind: "fiat",
    logoid: "country/LK",
  },
  {
    id: "LRD",
    code: "LRD",
    description: "Liberian Dollar",
    kind: "fiat",
    logoid: "country/LR",
  },
  {
    id: "LSL",
    code: "LSL",
    description: "Lesotho Loti",
    kind: "fiat",
    logoid: "country/LS",
  },
  {
    id: "LYD",
    code: "LYD",
    description: "Libyan Dinar",
    kind: "fiat",
    logoid: "country/LY",
  },
  {
    id: "MAD",
    code: "MAD",
    description: "Moroccan Dirham",
    kind: "fiat",
    logoid: "country/MA",
  },
  {
    id: "MDL",
    code: "MDL",
    description: "Moldovan Leu",
    kind: "fiat",
    logoid: "country/MD",
  },
  {
    id: "MGA",
    code: "MGA",
    description: "Malagasy Ariary",
    kind: "fiat",
    logoid: "country/MG",
  },
  {
    id: "MKD",
    code: "MKD",
    description: "Macedonian Denar",
    kind: "fiat",
    logoid: "country/MK",
  },
  {
    id: "MMK",
    code: "MMK",
    description: "Myanmar Kyat",
    kind: "fiat",
    logoid: "country/MM",
  },
  {
    id: "MNT",
    code: "MNT",
    description: "Mongolian Tugrik",
    kind: "fiat",
    logoid: "country/MN",
  },
  {
    id: "MOP",
    code: "MOP",
    description: "Macanese Pataca",
    kind: "fiat",
    logoid: "country/MO",
  },
  {
    id: "MRU",
    code: "MRU",
    description: "Ouguiya",
    kind: "fiat",
    logoid: "country/MR",
  },
  {
    id: "MUR",
    code: "MUR",
    description: "Mauritian Rupee",
    kind: "fiat",
    logoid: "country/MU",
  },
  {
    id: "MVR",
    code: "MVR",
    description: "Maldivian Rufiyaa",
    kind: "fiat",
    logoid: "country/MV",
  },
  {
    id: "MWK",
    code: "MWK",
    description: "Malawian Kwacha",
    kind: "fiat",
    logoid: "country/MW",
  },
  {
    id: "MXN",
    code: "MXN",
    description: "Mexican Peso",
    kind: "fiat",
    logoid: "country/MX",
  },
  {
    id: "MXV",
    code: "MXV",
    description: "Mexican Investment Unit",
    kind: "fiat",
    logoid: "country/MX",
  },
  {
    id: "MYR",
    code: "MYR",
    description: "Malaysian Ringgit",
    kind: "fiat",
    logoid: "country/MY",
  },
  {
    id: "MZN",
    code: "MZN",
    description: "Mozambican Metical",
    kind: "fiat",
    logoid: "country/MZ",
  },
  {
    id: "NAD",
    code: "NAD",
    description: "Namibian Dollar",
    kind: "fiat",
    logoid: "country/NA",
  },
  {
    id: "NGN",
    code: "NGN",
    description: "Nigerian Naira",
    kind: "fiat",
    logoid: "country/NG",
  },
  {
    id: "NIO",
    code: "NIO",
    description: "Nicaraguan Córdoba",
    kind: "fiat",
    logoid: "country/NI",
  },
  {
    id: "NOK",
    code: "NOK",
    description: "Norwegian Krone",
    kind: "fiat",
    logoid: "country/NO",
  },
  {
    id: "NPR",
    code: "NPR",
    description: "Nepalese Rupee",
    kind: "fiat",
    logoid: "country/NP",
  },
  {
    id: "NZD",
    code: "NZD",
    description: "New Zealand Dollar",
    kind: "fiat",
    logoid: "country/NZ",
  },
  {
    id: "OMR",
    code: "OMR",
    description: "Omani Rial",
    kind: "fiat",
    logoid: "country/OM",
  },
  {
    id: "PAB",
    code: "PAB",
    description: "Panamanian Balboa",
    kind: "fiat",
    logoid: "country/PA",
  },
  {
    id: "PEN",
    code: "PEN",
    description: "Peruvian Sol",
    kind: "fiat",
    logoid: "country/PE",
  },
  {
    id: "PGK",
    code: "PGK",
    description: "Papua New Guinean Kina",
    kind: "fiat",
    logoid: "country/PG",
  },
  {
    id: "PHP",
    code: "PHP",
    description: "Philippine Peso",
    kind: "fiat",
    logoid: "country/PH",
  },
  {
    id: "PKR",
    code: "PKR",
    description: "Pakistani Rupee",
    kind: "fiat",
    logoid: "country/PK",
  },
  {
    id: "PLN",
    code: "PLN",
    description: "Polish Zloty",
    kind: "fiat",
    logoid: "country/PL",
  },
  {
    id: "PYG",
    code: "PYG",
    description: "Paraguayan Guarani",
    kind: "fiat",
    logoid: "country/PY",
  },
  {
    id: "QAR",
    code: "QAR",
    description: "Qatari Rial",
    kind: "fiat",
    logoid: "country/QA",
  },
  {
    id: "RON",
    code: "RON",
    description: "Romanian Leu",
    kind: "fiat",
    logoid: "country/RO",
  },
  {
    id: "RSD",
    code: "RSD",
    description: "Serbian Dinar",
    kind: "fiat",
    logoid: "country/RS",
  },
  {
    id: "RUB",
    code: "RUB",
    description: "Russian Ruble",
    kind: "fiat",
    logoid: "country/RU",
  },
  {
    id: "RWF",
    code: "RWF",
    description: "Rwandan Franc",
    kind: "fiat",
    logoid: "country/RW",
  },
  {
    id: "SANTAPEPE",
    code: "SANTAPEPE",
    description: "PEPEUSDT",
  },
  {
    id: "SAR",
    code: "SAR",
    description: "Saudi Riyal",
    kind: "fiat",
    logoid: "country/SA",
  },
  {
    id: "SBD",
    code: "SBD",
    description: "Solomon Islands Dollar",
    kind: "fiat",
    logoid: "country/SB",
  },
  {
    id: "SCR",
    code: "SCR",
    description: "Seychellois Rupee",
    kind: "fiat",
    logoid: "country/SC",
  },
  {
    id: "SDG",
    code: "SDG",
    description: "Sudanese Pound",
    kind: "fiat",
    logoid: "country/SD",
  },
  {
    id: "SEK",
    code: "SEK",
    description: "Swedish Krona",
    kind: "fiat",
    logoid: "country/SE",
  },
  {
    id: "SGD",
    code: "SGD",
    description: "Singapore Dollar",
    kind: "fiat",
    logoid: "country/SG",
  },
  {
    id: "SLL",
    code: "SLL",
    description: "Sierra Leonean Leone",
    kind: "fiat",
    logoid: "country/SL",
  },
  {
    id: "SOS",
    code: "SOS",
    description: "Somali Shilling",
    kind: "fiat",
    logoid: "country/SO",
  },
  {
    id: "SRD",
    code: "SRD",
    description: "Surinamese Dollar",
    kind: "fiat",
    logoid: "country/SR",
  },
  {
    id: "STN",
    code: "STN",
    description: "Sao Tome and Principe dobra",
    kind: "fiat",
    logoid: "country/ST",
  },
  {
    id: "SVC",
    code: "SVC",
    description: "Salvadoran Colón",
    kind: "fiat",
    logoid: "country/SV",
  },
  {
    id: "SYP",
    code: "SYP",
    description: "Syrian Pound",
    kind: "fiat",
    logoid: "country/SY",
  },
  {
    id: "SZL",
    code: "SZL",
    description: "Swazi Lilangeni",
    kind: "fiat",
    logoid: "country/SZ",
  },
  {
    id: "THB",
    code: "THB",
    description: "Thai Baht",
    kind: "fiat",
    logoid: "country/TH",
  },
  {
    id: "TJS",
    code: "TJS",
    description: "Tajikistani Somoni",
    kind: "fiat",
    logoid: "country/TJ",
  },
  {
    id: "TMT",
    code: "TMT",
    description: "Turkmenistani Manat",
    kind: "fiat",
    logoid: "country/TM",
  },
  {
    id: "TND",
    code: "TND",
    description: "Tunisian Dinar",
    kind: "fiat",
    logoid: "country/TN",
  },
  {
    id: "TOP",
    code: "TOP",
    description: "Tongan Paʻanga",
    kind: "fiat",
    logoid: "country/TO",
  },
  {
    id: "TRY",
    code: "TRY",
    description: "Turkish Lira",
    kind: "fiat",
    logoid: "country/TR",
  },
  {
    id: "TTD",
    code: "TTD",
    description: "Trinidad & Tobago Dollar",
    kind: "fiat",
    logoid: "country/TT",
  },
  {
    id: "TWD",
    code: "TWD",
    description: "New Taiwan Dollar",
    kind: "fiat",
    logoid: "country/TW",
  },
  {
    id: "TZS",
    code: "TZS",
    description: "Tanzanian Shilling",
    kind: "fiat",
    logoid: "country/TZ",
  },
  {
    id: "UAH",
    code: "UAH",
    description: "Ukrainian Hryvnia",
    kind: "fiat",
    logoid: "country/UA",
  },
  {
    id: "UGX",
    code: "UGX",
    description: "Ugandan Shilling",
    kind: "fiat",
    logoid: "country/UG",
  },
  {
    id: "USD",
    code: "USD",
    description: "US Dollar",
    kind: "fiat",
    logoid: "country/US",
  },
  {
    id: "UYU",
    code: "UYU",
    description: "Uruguayan Peso",
    kind: "fiat",
    logoid: "country/UY",
  },
  {
    id: "UZS",
    code: "UZS",
    description: "Uzbekistani Som",
    kind: "fiat",
    logoid: "country/UZ",
  },
  {
    id: "VES",
    code: "VES",
    description: "Bolívar Soberano",
    kind: "fiat",
    logoid: "country/VE",
  },
  {
    id: "VND",
    code: "VND",
    description: "Vietnamese Dong",
    kind: "fiat",
    logoid: "country/VN",
  },
  {
    id: "VUV",
    code: "VUV",
    description: "Vanuatu Vatu",
    kind: "fiat",
    logoid: "country/VU",
  },
  {
    id: "WST",
    code: "WST",
    description: "Samoan Tala",
    kind: "fiat",
    logoid: "country/WS",
  },
  {
    id: "XAF",
    code: "XAF",
    description: "Central African CFA Franc",
    kind: "fiat",
    logoid: "country/CF",
  },
  {
    id: "XCD",
    code: "XCD",
    description: "East Caribbean Dollar",
    kind: "fiat",
    logoid: "country/AG",
  },
  {
    id: "XDR",
    code: "XDR",
    description: "SDR (Special Drawing Right)",
    kind: "fiat",
    logoid: "country/US",
  },
  {
    id: "XOF",
    code: "XOF",
    description: "West African CFA Franc",
    kind: "fiat",
    logoid: "country/BJ",
  },
  {
    id: "XPF",
    code: "XPF",
    description: "CFP Franc",
    kind: "fiat",
    logoid: "country/PF",
  },
  {
    id: "XTVATS",
    code: "ATS",
    description: "Austrian Schilling",
    kind: "fiat",
    logoid: "country/AT",
  },
  {
    id: "XTVBEF",
    code: "BEF",
    description: "Belgian Franc",
    kind: "fiat",
    logoid: "country/BE",
  },
  {
    id: "XTVC1INCH",
    code: "1INCH",
    description: "1inch Network",
    kind: "crypto",
    logoid: "crypto/XTVC1INCH",
  },
  {
    id: "XTVCAAVE",
    code: "AAVE",
    description: "Aave",
    kind: "crypto",
    logoid: "crypto/XTVCAAVE",
  },
  {
    id: "XTVCADA",
    code: "ADA",
    description: "Cardano",
    kind: "crypto",
    logoid: "crypto/XTVCADA",
  },
  {
    id: "XTVCALGO",
    code: "ALGO",
    description: "Algorand",
    kind: "crypto",
    logoid: "crypto/XTVCALGO",
  },
  {
    id: "XTVCANKR",
    code: "ANKR",
    description: "Ankr",
    kind: "crypto",
    logoid: "crypto/XTVCANKR",
  },
  {
    id: "XTVCATOM",
    code: "ATOM",
    description: "Cosmos",
    kind: "crypto",
    logoid: "crypto/XTVCATOM",
  },
  {
    id: "XTVCAVAX",
    code: "AVAX",
    description: "Avalanche",
    kind: "crypto",
    logoid: "crypto/XTVCAVAX",
  },
  {
    id: "XTVCAXS",
    code: "AXS",
    description: "Axie Infinity",
    kind: "crypto",
    logoid: "crypto/XTVCAXS",
  },
  {
    id: "XTVCBAT",
    code: "BAT",
    description: "Basic Attention Token",
    kind: "crypto",
    logoid: "crypto/XTVCBAT",
  },
  {
    id: "XTVCBCH",
    code: "BCH",
    description: "Bitcoin Cash",
    kind: "crypto",
    logoid: "crypto/XTVCBCH",
  },
  {
    id: "XTVCBNB",
    code: "BNB",
    description: "BNB",
    kind: "crypto",
    logoid: "crypto/XTVCBNB",
  },
  {
    id: "XTVCBNT",
    code: "BNT",
    description: "Bancor",
    kind: "crypto",
    logoid: "crypto/XTVCBNT",
  },
  {
    id: "XTVCBSV",
    code: "BSV",
    description: "Bitcoin SV",
    kind: "crypto",
    logoid: "crypto/XTVCBSV",
  },
  {
    id: "XTVCBTC",
    code: "BTC",
    description: "Bitcoin",
    kind: "crypto",
    logoid: "crypto/XTVCBTC",
  },
  {
    id: "XTVCCAKE",
    code: "CAKE",
    description: "PancakeSwap",
    kind: "crypto",
    logoid: "crypto/XTVCCAKE",
  },
  {
    id: "XTVCCKB",
    code: "CKB",
    description: "Nervos Network",
    kind: "crypto",
    logoid: "crypto/XTVCCKB",
  },
  {
    id: "XTVCCOMP",
    code: "COMP",
    description: "Compound",
    kind: "crypto",
    logoid: "crypto/XTVCCOMP",
  },
  {
    id: "XTVCCOTI",
    code: "COTI",
    description: "COTI",
    kind: "crypto",
    logoid: "crypto/XTVCCOTI",
  },
  {
    id: "XTVCCRV",
    code: "CRV",
    description: "Curve DAO Token",
    kind: "crypto",
    logoid: "crypto/XTVCCRV",
  },
  {
    id: "XTVCDAI",
    code: "DAI",
    description: "Dai",
    kind: "crypto",
    logoid: "crypto/XTVCDAI",
  },
  {
    id: "XTVCDFI",
    code: "DFI",
    description: "DeFiChain",
    kind: "crypto",
    logoid: "crypto/XTVCDFI",
  },
  {
    id: "XTVCDOGE",
    code: "DOGE",
    description: "Dogecoin",
    kind: "crypto",
    logoid: "crypto/XTVCDOGE",
  },
  {
    id: "XTVCDOT",
    code: "DOT",
    description: "Polkadot",
    kind: "crypto",
    logoid: "crypto/XTVCDOT",
  },
  {
    id: "XTVCDYDX",
    code: "ETHDYDX",
    description: "dYdX (ethDYDX)",
    kind: "crypto",
    logoid: "crypto/XTVCDYDX",
  },
  {
    id: "XTVCEGLD",
    code: "EGLD",
    description: "MultiversX",
    kind: "crypto",
    logoid: "crypto/XTVCEGLD",
  },
  {
    id: "XTVCEOS",
    code: "EOS",
    description: "EOS",
    kind: "crypto",
    logoid: "crypto/XTVCEOS",
  },
  {
    id: "XTVCETC",
    code: "ETC",
    description: "Ethereum Classic",
    kind: "crypto",
    logoid: "crypto/XTVCETC",
  },
  {
    id: "XTVCETH",
    code: "ETH",
    description: "Ethereum",
    kind: "crypto",
    logoid: "crypto/XTVCETH",
  },
  {
    id: "XTVCFIL",
    code: "FIL",
    description: "Filecoin",
    kind: "crypto",
    logoid: "crypto/XTVCFIL",
  },
  {
    id: "XTVCFTM",
    code: "FTM",
    description: "Fantom",
    kind: "crypto",
    logoid: "crypto/XTVCFTM",
  },
  {
    id: "XTVCFTT",
    code: "FTT",
    description: "FTX Token",
    kind: "crypto",
    logoid: "crypto/XTVCFTT",
  },
  {
    id: "XTVCFXS",
    code: "FXS",
    description: "Frax Share",
    kind: "crypto",
    logoid: "crypto/XTVCFXS",
  },
  {
    id: "XTVCGNO",
    code: "GNO",
    description: "Gnosis",
    kind: "crypto",
    logoid: "crypto/XTVCGNO",
  },
  {
    id: "XTVCGRT",
    code: "GRT",
    description: "The Graph",
    kind: "crypto",
    logoid: "crypto/XTVCGRAPH",
  },
  {
    id: "XTVCHBAR",
    code: "HBAR",
    description: "Hedera",
    kind: "crypto",
    logoid: "crypto/XTVCHBAR",
  },
  {
    id: "XTVCHEX",
    code: "HEX",
    description: "HEX",
    kind: "crypto",
    logoid: "crypto/XTVCHEX",
  },
  {
    id: "XTVCHIT",
    code: "HIT",
    description: "HitChain",
    kind: "crypto",
    logoid: "crypto/XTVCHIT",
  },
  {
    id: "XTVCHNT",
    code: "HNT",
    description: "Helium",
    kind: "crypto",
    logoid: "crypto/XTVCHNT",
  },
  {
    id: "XTVCHOT",
    code: "HOT",
    description: "Holo",
    kind: "crypto",
    logoid: "crypto/XTVCHOT",
  },
  {
    id: "XTVCICP",
    code: "ICP",
    description: "Internet Computer",
    kind: "crypto",
    logoid: "crypto/XTVCICP",
  },
  {
    id: "XTVCIOTA",
    code: "IOTA",
    description: "IOTA",
    kind: "crypto",
    logoid: "crypto/XTVCIOTA",
  },
  {
    id: "XTVCKAVA",
    code: "KAVA",
    description: "Kava",
    kind: "crypto",
    logoid: "crypto/XTVCKAVA",
  },
  {
    id: "XTVCKEEP",
    code: "KEEP",
    description: "Keep Network",
    kind: "crypto",
    logoid: "crypto/XTVCKEEP",
  },
  {
    id: "XTVCKLAY",
    code: "KLAY",
    description: "Klaytn",
    kind: "crypto",
    logoid: "crypto/XTVCKLAY",
  },
  {
    id: "XTVCKNC",
    code: "KNC",
    description: "Kyber Network Crystal v2",
    kind: "crypto",
    logoid: "crypto/XTVCKNC",
  },
  {
    id: "XTVCLEO",
    code: "LEO",
    description: "UNUS SED LEO",
    kind: "crypto",
    logoid: "crypto/XTVCLEO",
  },
  {
    id: "XTVCLINK",
    code: "LINK",
    description: "Chainlink",
    kind: "crypto",
    logoid: "crypto/XTVCLINK",
  },
  {
    id: "XTVCLRC",
    code: "LRC",
    description: "Loopring",
    kind: "crypto",
    logoid: "crypto/XTVCLRC",
  },
  {
    id: "XTVCLTC",
    code: "LTC",
    description: "Litecoin",
    kind: "crypto",
    logoid: "crypto/XTVCLTC",
  },
  {
    id: "XTVCLUNA",
    code: "LUNA",
    description: "Terra",
    kind: "crypto",
    logoid: "crypto/XTVCLUNA",
  },
  {
    id: "XTVCMANA",
    code: "MANA",
    description: "Decentraland",
    kind: "crypto",
    logoid: "crypto/XTVCMANA",
  },
  {
    id: "XTVCMATIC",
    code: "MATIC",
    description: "Polygon",
    kind: "crypto",
    logoid: "crypto/XTVCMATIC",
  },
  {
    id: "XTVCMKR",
    code: "MKR",
    description: "Maker",
    kind: "crypto",
    logoid: "crypto/XTVCMKR",
  },
  {
    id: "XTVCNEAR",
    code: "NEAR",
    description: "NEAR Protocol",
    kind: "crypto",
    logoid: "crypto/XTVCNEAR",
  },
  {
    id: "XTVCNH",
    code: "CNH",
    description: "Offshore Yuan Renminbi",
    kind: "fiat",
    logoid: "country/CN",
  },
  {
    id: "XTVCOCEAN",
    code: "OCEAN",
    description: "Ocean Protocol",
    kind: "crypto",
    logoid: "crypto/XTVCOCEAN",
  },
  {
    id: "XTVCONE",
    code: "ONE",
    description: "Harmony",
    kind: "crypto",
    logoid: "crypto/XTVCONE",
  },
  {
    id: "XTVCPERP",
    code: "PERP",
    description: "Perpetual Protocol",
    kind: "crypto",
    logoid: "crypto/XTVCPERP",
  },
  {
    id: "XTVCREN",
    code: "REN",
    description: "Ren",
    kind: "crypto",
    logoid: "crypto/XTVCREN",
  },
  {
    id: "XTVCRENBTC",
    code: "RENBTC",
    description: "renBTC",
    kind: "crypto",
    logoid: "crypto/XTVCRENBTC",
  },
  {
    id: "XTVCREQ",
    code: "REQ",
    description: "Request",
    kind: "crypto",
    logoid: "crypto/XTVCREQ",
  },
  {
    id: "XTVCROSE",
    code: "ROSE",
    description: "Oasis",
    kind: "crypto",
    logoid: "crypto/XTVCROSE",
  },
  {
    id: "XTVCRSR",
    code: "RSR",
    description: "Reserve Rights",
    kind: "crypto",
    logoid: "crypto/XTVCRSR",
  },
  {
    id: "XTVCRUNE",
    code: "RUNE",
    description: "THORChain",
    kind: "crypto",
    logoid: "crypto/XTVCRUNE",
  },
  {
    id: "XTVCSAND",
    code: "SAND",
    description: "The Sandbox",
    kind: "crypto",
    logoid: "crypto/XTVCSAND",
  },
  {
    id: "XTVCSCRT",
    code: "SCRT",
    description: "Secret",
    kind: "crypto",
    logoid: "crypto/XTVCSCRT",
  },
  {
    id: "XTVCSHIB",
    code: "SHIB",
    description: "Shiba Inu",
    kind: "crypto",
    logoid: "crypto/XTVCSHIB",
  },
  {
    id: "XTVCSNX",
    code: "SNX",
    description: "Synthetix",
    kind: "crypto",
    logoid: "crypto/XTVCSNX",
  },
  {
    id: "XTVCSOL",
    code: "SOL",
    description: "Solana",
    kind: "crypto",
    logoid: "crypto/XTVCSOL",
  },
  {
    id: "XTVCSRM",
    code: "SRM",
    description: "Serum",
    kind: "crypto",
    logoid: "crypto/XTVCSRM",
  },
  {
    id: "XTVCSUSHI",
    code: "SUSHI",
    description: "SushiSwap",
    kind: "crypto",
    logoid: "crypto/XTVCSUSHI",
  },
  {
    id: "XTVCSXP",
    code: "SXP",
    description: "Solar",
    kind: "crypto",
    logoid: "crypto/XTVCSXP",
  },
  {
    id: "XTVCTHETA",
    code: "THETA",
    description: "Theta Network",
    kind: "crypto",
    logoid: "crypto/XTVCTHETA",
  },
  {
    id: "XTVCTLOS",
    code: "TLOS",
    description: "Telos",
    kind: "crypto",
    logoid: "crypto/XTVCTLOS",
  },
  {
    id: "XTVCTON",
    code: "TON",
    description: "Toncoin",
    kind: "crypto",
    logoid: "crypto/XTVCTON",
  },
  {
    id: "XTVCTRIBE",
    code: "TRIBE",
    description: "Tribe",
    kind: "crypto",
    logoid: "crypto/XTVCTRIBE",
  },
  {
    id: "XTVCTRX",
    code: "TRX",
    description: "TRON",
    kind: "crypto",
    logoid: "crypto/XTVCTRX",
  },
  {
    id: "XTVCUMA",
    code: "UMA",
    description: "UMA",
    kind: "crypto",
    logoid: "crypto/XTVCUMA",
  },
  {
    id: "XTVCUNI",
    code: "UNI",
    description: "Uniswap",
    kind: "crypto",
    logoid: "crypto/XTVCUNI",
  },
  {
    id: "XTVCUSDC",
    code: "USDC",
    description: "USDC",
    kind: "crypto",
    logoid: "crypto/XTVCUSDC",
  },
  {
    id: "XTVCUSDT",
    code: "USDT",
    description: "Tether USDt",
    kind: "crypto",
    logoid: "crypto/XTVCUSDT",
  },
  {
    id: "XTVCVET",
    code: "VET",
    description: "VeChain",
    kind: "crypto",
    logoid: "crypto/XTVCVET",
  },
  {
    id: "XTVCWBTC",
    code: "WBTC",
    description: "Wrapped Bitcoin",
    kind: "crypto",
    logoid: "crypto/XTVCWBTC",
  },
  {
    id: "XTVCXLM",
    code: "XLM",
    description: "Stellar",
    kind: "crypto",
    logoid: "crypto/XTVCXLM",
  },
  {
    id: "XTVCXMR",
    code: "XMR",
    description: "Monero",
    kind: "crypto",
    logoid: "crypto/XTVCXMR",
  },
  {
    id: "XTVCXRP",
    code: "XRP",
    description: "XRP",
    kind: "crypto",
    logoid: "crypto/XTVCXRP",
  },
  {
    id: "XTVCXTZ",
    code: "XTZ",
    description: "Tezos",
    kind: "crypto",
    logoid: "crypto/XTVCXTZ",
  },
  {
    id: "XTVCYFI",
    code: "YFI",
    description: "yearn.finance",
    kind: "crypto",
    logoid: "crypto/XTVCYFI",
  },
  {
    id: "XTVCZRX",
    code: "ZRX",
    description: "0x Protocol",
    kind: "crypto",
    logoid: "crypto/XTVCZRX",
  },
  {
    id: "XTVDEM",
    code: "DEM",
    description: "German Mark",
    kind: "fiat",
    logoid: "country/DE",
  },
  {
    id: "XTVESP",
    code: "ESP",
    description: "Spanish Peseta",
    kind: "fiat",
    logoid: "country/ES",
  },
  {
    id: "XTVFIM",
    code: "FIM",
    description: "Finnish Markka",
    kind: "fiat",
    logoid: "country/FI",
  },
  {
    id: "XTVFRF",
    code: "FRF",
    description: "French Franc",
    kind: "fiat",
    logoid: "country/FR",
  },
  {
    id: "XTVGBX",
    code: "GBX",
    description: "Pence Sterling",
    kind: "fiat",
    logoid: "country/GB",
  },
  {
    id: "XTVGRD",
    code: "GRD",
    description: "Greek Drachma",
    kind: "fiat",
    logoid: "country/GR",
  },
  {
    id: "XTVIEP",
    code: "IEP",
    description: "Irish Pound",
    kind: "fiat",
    logoid: "country/IE",
  },
  {
    id: "XTVILA",
    code: "ILA",
    description: "Israeli Agorot",
    kind: "fiat",
    logoid: "country/IL",
  },
  {
    id: "XTVITL",
    code: "ITL",
    description: "Italian Lira",
    kind: "fiat",
    logoid: "country/IT",
  },
  {
    id: "XTVKWF",
    code: "KWF",
    description: "Kuwaiti Fils",
    kind: "fiat",
    logoid: "country/KW",
  },
  {
    id: "XTVLUF",
    code: "LUF",
    description: "Luxembourgian Franc",
    kind: "fiat",
    logoid: "country/LU",
  },
  {
    id: "XTVNLG",
    code: "NLG",
    description: "Dutch Guilder",
    kind: "fiat",
    logoid: "country/NL",
  },
  {
    id: "XTVPTE",
    code: "PTE",
    description: "Portuguese Escudo",
    kind: "fiat",
    logoid: "country/PT",
  },
  {
    id: "XTVSIT",
    code: "SIT",
    description: "Slovenian Tolar",
    kind: "fiat",
    logoid: "country/SI",
  },
  {
    id: "XTVUSX",
    code: "USX",
    description: "U.S. Cents",
    kind: "fiat",
    logoid: "country/US",
  },
  {
    id: "XTVZAC",
    code: "ZAC",
    description: "South African Cents",
    kind: "fiat",
    logoid: "country/ZA",
  },
  {
    id: "YER",
    code: "YER",
    description: "Yemeni Rial",
    kind: "fiat",
    logoid: "country/YE",
  },
  {
    id: "ZAR",
    code: "ZAR",
    description: "South African Rand",
    kind: "fiat",
    logoid: "country/ZA",
  },
  {
    id: "ZMW",
    code: "ZMW",
    description: "Zambian Kwacha",
    kind: "fiat",
    logoid: "country/ZM",
  },
  {
    id: "PLEDGE",
    code: "PLEDGE",
    description: "Y59",
  },
  {
    id: "OMNIT",
    code: "OMNIT",
    description: "OMNITRY",
  },
];
module.exports = { currency };
